<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            [
                'title' => 'Marrakech: The most beautiful touristic city',
                'content' => 'Easily one of the most beautiful and fascinating cities in Morocco, no trip to Northern Africa is complete without checking out Marrakech. This 1000-year-old city is home to a thriving medina, amazing shopping, and some of the most gorgeous architecture you’ll find anywhere in the world. Marrakech is also famous for its beautiful riads (guesthouses often converted from family homes) and you’ll find amazing little boutique riads dotting winding streets all over the city. Ready to fall in love with Morocco? Here’s the ultimate Marrakech travel guide.',
                'user_id' => 1,
            ],[
                'title' => 'Everything you need to know before visiting Rabat',
                'content' => 'Morocco’s major airport is in Casablanca however there is a Rabat airport. Most flights that arrive here are either domestic or limited flights from Europe. Chances are you’ll arrive in Rabat from a land entry; train, bus, or car. Which you choose may depend on your budget and how you plan to travel in Morocco.To get from Rabat to Casablanca (or vice versa) the easiest option is likely the train. There are three train stations in Casablanca that can be your starting point to reach Rabat. Casa Oasis, Casa Voyageur, and Casa Port. Casa Oasis is the first train station arrival point if you’re taking the train from Casablanca airport to the city. From here you would change trains, reaching Casa Voyageur as the second station and onward to Rabat. You will want to buy a ticket that takes you to Rabat Ville, the main train station in Rabat. If you are departing from the city of Casablanca head to Casa Port station where there are regular commuter trains to Rabat leaving twice an hour. (Find full time tables on the ONCF website).You can reach Rabat from other cities as well. Simply check the timetable and purchase your ticket to the appropriate station.A second option to reach Rabat is to use the bus system. I recommend Supratours buses as they are reliable, comfortable and have few mechanical issues. Not all cities will have buses to Rabat, as they try to reach places where there is limited train service to give another option. You may need to use the public bus system. These buses depart from the main depot in each city. The schedules can be erratic, and buses overcrowded, however they are very inexpensive.A third option to reach Rabat is by car. You can buy a seat in a shared grand taxi or you can hire a driver to take you privately. If you would like to navigate the taxi system, take a read of this post on getting around Morocco. Private drivers can be arranged through your accommodation. The usually have direct contact with drivers or taxis that can be hired to take you to your destination. This is often the fastest way to travel however it is also the most expensive.',
                'user_id' => 1,
            ],[
                'title' => 'Best things to do in Fez. A guide to Morocco\'s ancient city',
                'content' => 'Fez is famous for its ancient walled city Fez el Bali, the best-preserved medina in the Arab world and home to the world’s oldest university. A city many compare to the old walled city of Jerusalem. Covering an area of approx 2.8 square km, with an estimated 9500 streets, it is one of the world’s most significant car-free urban areas.There is an impalpable rawness about a place where more than 150,000 people still choose to live in the dark confines of an ancient, dense, and dilapidated medina.Fez is a fascinating and overwhelming city. The locals of this ancient city are different to any others you will meet in Morocco, and constant references to things ‘outside the wall’ makes you realise people do live their whole lives in this medieval maze of commerce.Fez offers a far more authentic and atmospheric experience than more popular Marrakech. A city now swamped with luxury hotels, designer shops and tour buses.So if you were to ask; Fez or Marrakech? Fez is the destination of choice for travellers seeking a genuine, donkeys, crowds, bad smells and all travel experience. Fez is the Morocco you come to see. A city where donkey and hand pulled cart is still the only means of transportation, and ruinous pockets loom around every corner. It is no wonder the entire Fez Medina is a designated Unesco World Heritage of Humanity Site.Unlike many other old cities around the world, like Dubrovnik in Croatia where locals have either been pushed out by tourism or moved to more modern urban developments, there is still a population of over 156,000 living in the Fez Medina.',
                'user_id' => 2,
            ],
            [
                'title' => 'Marrakech: The most beautiful touristic city',
                'content' => 'Easily one of the most beautiful and fascinating cities in Morocco, no trip to Northern Africa is complete without checking out Marrakech. This 1000-year-old city is home to a thriving medina, amazing shopping, and some of the most gorgeous architecture you’ll find anywhere in the world. Marrakech is also famous for its beautiful riads (guesthouses often converted from family homes) and you’ll find amazing little boutique riads dotting winding streets all over the city. Ready to fall in love with Morocco? Here’s the ultimate Marrakech travel guide.',
                'user_id' => 1,
            ],[
                'title' => 'Everything you need to know before visiting Rabat',
                'content' => 'Morocco’s major airport is in Casablanca however there is a Rabat airport. Most flights that arrive here are either domestic or limited flights from Europe. Chances are you’ll arrive in Rabat from a land entry; train, bus, or car. Which you choose may depend on your budget and how you plan to travel in Morocco.To get from Rabat to Casablanca (or vice versa) the easiest option is likely the train. There are three train stations in Casablanca that can be your starting point to reach Rabat. Casa Oasis, Casa Voyageur, and Casa Port. Casa Oasis is the first train station arrival point if you’re taking the train from Casablanca airport to the city. From here you would change trains, reaching Casa Voyageur as the second station and onward to Rabat. You will want to buy a ticket that takes you to Rabat Ville, the main train station in Rabat. If you are departing from the city of Casablanca head to Casa Port station where there are regular commuter trains to Rabat leaving twice an hour. (Find full time tables on the ONCF website).You can reach Rabat from other cities as well. Simply check the timetable and purchase your ticket to the appropriate station.A second option to reach Rabat is to use the bus system. I recommend Supratours buses as they are reliable, comfortable and have few mechanical issues. Not all cities will have buses to Rabat, as they try to reach places where there is limited train service to give another option. You may need to use the public bus system. These buses depart from the main depot in each city. The schedules can be erratic, and buses overcrowded, however they are very inexpensive.A third option to reach Rabat is by car. You can buy a seat in a shared grand taxi or you can hire a driver to take you privately. If you would like to navigate the taxi system, take a read of this post on getting around Morocco. Private drivers can be arranged through your accommodation. The usually have direct contact with drivers or taxis that can be hired to take you to your destination. This is often the fastest way to travel however it is also the most expensive.',
                'user_id' => 1,
            ],[
                'title' => 'Best things to do in Fez. A guide to Morocco\'s ancient city',
                'content' => 'Fez is famous for its ancient walled city Fez el Bali, the best-preserved medina in the Arab world and home to the world’s oldest university. A city many compare to the old walled city of Jerusalem. Covering an area of approx 2.8 square km, with an estimated 9500 streets, it is one of the world’s most significant car-free urban areas.There is an impalpable rawness about a place where more than 150,000 people still choose to live in the dark confines of an ancient, dense, and dilapidated medina.Fez is a fascinating and overwhelming city. The locals of this ancient city are different to any others you will meet in Morocco, and constant references to things ‘outside the wall’ makes you realise people do live their whole lives in this medieval maze of commerce.Fez offers a far more authentic and atmospheric experience than more popular Marrakech. A city now swamped with luxury hotels, designer shops and tour buses.So if you were to ask; Fez or Marrakech? Fez is the destination of choice for travellers seeking a genuine, donkeys, crowds, bad smells and all travel experience. Fez is the Morocco you come to see. A city where donkey and hand pulled cart is still the only means of transportation, and ruinous pockets loom around every corner. It is no wonder the entire Fez Medina is a designated Unesco World Heritage of Humanity Site.Unlike many other old cities around the world, like Dubrovnik in Croatia where locals have either been pushed out by tourism or moved to more modern urban developments, there is still a population of over 156,000 living in the Fez Medina.',
                'user_id' => 2,
            ],
            [
                'title' => 'Marrakech: The most beautiful touristic city',
                'content' => 'Easily one of the most beautiful and fascinating cities in Morocco, no trip to Northern Africa is complete without checking out Marrakech. This 1000-year-old city is home to a thriving medina, amazing shopping, and some of the most gorgeous architecture you’ll find anywhere in the world. Marrakech is also famous for its beautiful riads (guesthouses often converted from family homes) and you’ll find amazing little boutique riads dotting winding streets all over the city. Ready to fall in love with Morocco? Here’s the ultimate Marrakech travel guide.',
                'user_id' => 1,
            ],[
                'title' => 'Everything you need to know before visiting Rabat',
                'content' => 'Morocco’s major airport is in Casablanca however there is a Rabat airport. Most flights that arrive here are either domestic or limited flights from Europe. Chances are you’ll arrive in Rabat from a land entry; train, bus, or car. Which you choose may depend on your budget and how you plan to travel in Morocco.To get from Rabat to Casablanca (or vice versa) the easiest option is likely the train. There are three train stations in Casablanca that can be your starting point to reach Rabat. Casa Oasis, Casa Voyageur, and Casa Port. Casa Oasis is the first train station arrival point if you’re taking the train from Casablanca airport to the city. From here you would change trains, reaching Casa Voyageur as the second station and onward to Rabat. You will want to buy a ticket that takes you to Rabat Ville, the main train station in Rabat. If you are departing from the city of Casablanca head to Casa Port station where there are regular commuter trains to Rabat leaving twice an hour. (Find full time tables on the ONCF website).You can reach Rabat from other cities as well. Simply check the timetable and purchase your ticket to the appropriate station.A second option to reach Rabat is to use the bus system. I recommend Supratours buses as they are reliable, comfortable and have few mechanical issues. Not all cities will have buses to Rabat, as they try to reach places where there is limited train service to give another option. You may need to use the public bus system. These buses depart from the main depot in each city. The schedules can be erratic, and buses overcrowded, however they are very inexpensive.A third option to reach Rabat is by car. You can buy a seat in a shared grand taxi or you can hire a driver to take you privately. If you would like to navigate the taxi system, take a read of this post on getting around Morocco. Private drivers can be arranged through your accommodation. The usually have direct contact with drivers or taxis that can be hired to take you to your destination. This is often the fastest way to travel however it is also the most expensive.',
                'user_id' => 1,
            ],[
                'title' => 'Best things to do in Fez. A guide to Morocco\'s ancient city',
                'content' => 'Fez is famous for its ancient walled city Fez el Bali, the best-preserved medina in the Arab world and home to the world’s oldest university. A city many compare to the old walled city of Jerusalem. Covering an area of approx 2.8 square km, with an estimated 9500 streets, it is one of the world’s most significant car-free urban areas.There is an impalpable rawness about a place where more than 150,000 people still choose to live in the dark confines of an ancient, dense, and dilapidated medina.Fez is a fascinating and overwhelming city. The locals of this ancient city are different to any others you will meet in Morocco, and constant references to things ‘outside the wall’ makes you realise people do live their whole lives in this medieval maze of commerce.Fez offers a far more authentic and atmospheric experience than more popular Marrakech. A city now swamped with luxury hotels, designer shops and tour buses.So if you were to ask; Fez or Marrakech? Fez is the destination of choice for travellers seeking a genuine, donkeys, crowds, bad smells and all travel experience. Fez is the Morocco you come to see. A city where donkey and hand pulled cart is still the only means of transportation, and ruinous pockets loom around every corner. It is no wonder the entire Fez Medina is a designated Unesco World Heritage of Humanity Site.Unlike many other old cities around the world, like Dubrovnik in Croatia where locals have either been pushed out by tourism or moved to more modern urban developments, there is still a population of over 156,000 living in the Fez Medina.',
                'user_id' => 2,
            ],
        ]);
    }
}
